# Generated by Django 5.1.6 on 2025-03-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_file', models.FileField(blank=True, null=True, upload_to='uploads/sections')),
                ('status', models.BooleanField(default=False)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_status', models.BooleanField(default=False)),
                ('section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='pdf.sections')),
                ('tpdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.pdf')),
            ],
        ),
    ]
