# Generated by Django 5.1.6 on 2025-03-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_timeslots_date_alter_timeslots_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='timeslots',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='timeslots',
            name='section_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sections'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='section_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='sesction_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='sections',
        ),
    ]
