# Generated by Django 5.1.6 on 2025-03-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_remove_timeslots_section_alter_timeslots_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='section_file',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='sesction_status',
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_file', models.FileField(blank=True, null=True, upload_to='uploads/sections')),
                ('status', models.BooleanField(default=False)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='users.pdf')),
            ],
        ),
        migrations.AddField(
            model_name='timeslots',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='pdf.sections'),
        ),
    ]
