# Generated by Django 5.1.6 on 2025-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_remove_timeslots_section_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='section',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='section_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sections'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='section_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='sections',
        ),
    ]
