# Generated by Django 5.1.7 on 2025-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_remove_timeslots_section_timeslots_section_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='not_complete',
            field=models.BooleanField(default=False),
        ),
    ]
