# Generated by Django 5.1.6 on 2025-03-03 14:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/pdf/')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('total_sections', models.IntegerField(blank=True, null=True)),
                ('total_noof_timeslots', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=5)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('from_time', models.TimeField(default=datetime.time(18, 0))),
                ('to_time', models.TimeField(default=datetime.time(22, 0))),
                ('user_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
