# Generated by Django 5.1.7 on 2025-03-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pdf_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='structured',
            field=models.BooleanField(default=False),
        ),
    ]
